### ISSUE TITLE
Server making a request in a borrowed context?

### ISSUE THREAD

**Issue by chrismacklin** [martinisgroup/pylabrad#115]
Is there an example in the codebase for how to instruct a server to make a request to another server using the context of a client session?

For an explicit example: I have a server which stores a database initialized by a client and stored in that client's context on the database server.  I'd like another server to be able to query this database as if it were one of the clients.

**Comment by maffoo** [comment]
First, let me say that I'd recommend caution before you go too far down this road. We've found that sharing contexts in this way can be tricky, because you're trying to manage distributed state and it's very easy for things to get out of sync.

That said, it shouldn't be too hard to do what you want. The other server needs to know the context identifier, which is just a tuple of two 32-bit integers, so you'll have to send this to the other server, either by making a request to it from your client, or by sending the id explicitly as a cluster `(ww)`.

A few things to note:
- In server settings, the context data which gets passed as the second parameter (after `self`) has an attribute `ID` which gives the context identifier of this request. You can use this to make further requests in the same context.
- When you make a request to labrad in a particular context, if the first word (the "high" word) is zero, the manager will replace it with the connection ID instead. So, if you make a request to the second server in the context you want it to use, that would be fine, but if you send the context as a cluster of plain old data, then you'll have to do this replacement yourself because if the server makes a request in context `(0,x)` that is different from you making a request in context `(0,x)`. (I'll be the first to admit that treating contexts in this was was probably a bad idea, but, well, that's how it works currently.)

Here's a (schematic) example:
```python
# dict server
class DictServer(LabradServer):
    name = "dict_server"

    @setting(10, key='s', value='?')
    def set(self, c, key, value=None):
        c[key] = value

    @setting(11, key='s')
    def get(self, c, key):
        return c[key]

# other server
class ProxyServer(LabradServer):
    name = "proxy_server"

    @setting(11, server='s', key='s')
    def get_in_this_context(self, c, server, key):
        "Get from the specified server in this context"
        result = yield self.client[server].get(key, context=c.ID)
        returnValue(result)

    @setting(12, server='s', context='(ww)', key='s')
    def get_in_other_context(self, c, server, context, key):
        "Get from the specified server in the specified context"
        result = yield self.client[server].get(key, context=context)
        returnValue(result)

# client
>>> ctx1 = cxn.context()
>>> ctx2 = cxn.context()
>>> cxn.dict_server.set('a', 'one', context=ctx1)
>>> cxn.dict_server.set('a', 'two', context=ctx2)
>>> cxn.dict_server.get('a', context=ctx1)
'one'
>>> cxn.dict_server.get('a', context=ctx2)
'two'
>>> cxn.proxy_server.get_in_this_context('dict_server', 'a', context=ctx1)
'one'
>>> cxn.proxy_server.get_in_this_context('dict_server', 'a', context=ctx2)
'two'
>>> ctx1
(0, 2)
>>> cxn.proxy_server.get_in_other_context('dict_server', ctx1, 'a')
Exception: exceptions.KeyError: 'a'
# server made the request in context (0, 2), and the 0 got replaced with the _server's_
# connection ID, not our client ID. We have to translate manually if we pass it
# as plain old data
>>> cxn.proxy_server.get_in_other_context('dict_server', (cxn.ID, ctx1[1]), 'a')
'one'
```

**Comment by chrismacklin** [comment]
Thanks!  I'm not at all convinced this is the implementation I plan to use; this question was mostly prompted by curiosity from a re-read of part of the LabRAD spec in Markus' thesis.
