### ISSUE TITLE
Getting the floating point value of a unit seems to be broken

### ISSUE THREAD

**Issue by chrismacklin** [martinisgroup/pylabrad#116]
```python
v = Value(1.0, 'V')
float(v)
TypeError: Incompatible units: 'V', ''
v[''] # this is the contents of __float__ in Value/etc
TypeError: Incompatible units: 'V', ''
```
I can hack around this by just asking for ```v._value```, but, you know, best practices and all...

Also very confusing:
```python
v.unit.name
'V'
v.units()
TypeError: 'str' object is not callable
```
This one I can't figure out at all...

**Comment by maffoo** [comment]
The bracket notation returns the bare value of a dimensional quantity, expressed in the given units:
```python
>>> v = Value(1.0, 'V')
>>> v['V']
1.0
>>> v['mV']
1000.0
```
Volts have dimensions, so they can't be converted to empty, which is why you were seeing the error. If you have a dimensionless value, however, then you _can_ convert to empty units, because the dimensions are compatible. We allow calling `float` only on such a dimensionless number, to avoid losing unit information.
```python
>>> v = Value(1.0, 'mV/V')
>>> v['']
0.001
>>> float(v)
0.001
>>> v['uV/V']
1000.0
```

As for the other thing, the 'unit' attribute is a `Unit` object which has various properties of its own, while the 'units' attribute is a string (the unit name):
```python
>>> v = Value(1.0, 'V')
>>> v.unit
<Unit 'V'>
>>> v.unit.name
'V'
>>> v.units
'V'
```
This `units` property is redudundant, because you can just get the unit name (or do `str(v.unit)`) to get the string representation. It is really only there for historical reasons.

**Comment by chrismacklin** [comment]
Is there a recommended way to get the bare floating point value?  I need this for customized object serialization.
