### ISSUE TITLE
Check if an object can be flattened?

### ISSUE THREAD

**Issue by chrismacklin** [martinisgroup/pylabrad#117]
I'd like to create a server setting that returns a pre-serialized version of its reply if that reply cannot be flattened to a labrad type.  Is there a way to check this without going ahead and flattening it?  labrad.type.getType does not fail when handed an object that cannot be flattened; for instance
```python
labrad.types.getType([1, 2, "a"])
LRList(LRInt(), depth=1)
```

**Comment by maffoo** [comment]
I don't understand what you mean by returning a pre-serialized version. Anything you return from a server setting will get flattened before sending over the wire, so if something cannot be flattened and you try to return it, things will fail anyway. Can you describe in a bit more detail what you're trying to accomplish?

**Comment by chrismacklin** [comment]
As in, if the data cannot be flattened into a labrad type, I will resort to using a different serialization protocol than labrad (yaml for what I'm working on at the moment), send the data over the wire as a string, and then reconstruct on the user's end after receiving the server's reply.

**Comment by maffoo** [comment]
I'd say your best bet at the moment is just try to flatten and then fall back if there's an error. This [EAFP](https://docs.python.org/2/glossary.html#term-eafp) style is common in python. It may do some extra work, but as long as the size of objects you are sending is not huge, I would not expect performance to degrade much. And if the typing is fixed to fail when given non-flattenable data as in your example, the code will continue to work and just get faster.

One thing you may want to consider is that you can send a dict as a cluster of key-value clusters. Of course, this works best when you know the 'shape' of data and are not trying to nest things arbitrarily, since you need to know on the other side whether a cluster should be kept as a cluster, or turned into a dict; so this might not help much in your case.

**Comment by maffoo** [comment]
Also, it's certainly possible to add an array type; feel free to propose something :)

**Comment by DanielSank** [comment]
+1 A map type would be nice.
