### ISSUE TITLE
units - 'Ang' does not convert to 'm'

### ISSUE THREAD

**Issue by jayich** [martinisgroup/pylabrad#63]
```python
>>> from labrad import units
>>> a = units.WithUnit(1.0, 'Ang')
>>> a.inUnitsOf('m')
```
Gives the following error:
TypeError: Incompatible units: 'Ang', 'm'

Looking through the code 'Ang' seems to have base units of meters and should be convertible to meters.  I might be missing something here.  I didn't see an explicit test for inUnitsOf, I'll try and get to at least preforming a simple test on that method.  This might be easy for someone more familiar with units to fix quickly.

**Comment by maffoo** [comment]
There's no unit called 'Ang', however, there is a constant `Ang` defined in the units module with a value of 1e-10 m:
```python
>>> a = 1.0 * units.Ang
>>> a.inUnitsOf('m')
Value(1e-10, u'm')
```
The distinction is important because the labrad manager does not know about units called 'Ang', so we can't just define arbitrarily named units and expect them to be handled properly. We can, however, define arbitrary constants, and use them in computations.

**Comment by DanielSank** [comment]
> The distinction is important because the labrad manager does not know about units called 'Ang'

Just to be a pest: we really don't want the manager caring about dimensions anyway...

**Comment by jayich** [comment]
Ah,  I see.  Thank you.

**Comment by ejeffrey** [comment]
Even if we take the manager out of the equation we should still have a list
of preferred units that all clients are expected to understand.

Also, the labrad manager happily passes through units it doesn't understand
without conversion, the only problem is that the recipient won't
necessarily know what to do with it.

Evan
