### ISSUE TITLE
Why can't I specify '' as an optional type tag in @setting ?

### ISSUE THREAD

**Issue by DanielSank** [martinisgroup/pylabrad#71]
Why isn't this allowed?

```python
@setting(51, channel='i', coup=['','s'], returns='s')
```
When I try this python tells me
```python
Exception: '' not allowed after first arg.
```
I gather that the correct way to describe possibly null arguments is to just default them to `None` in the function signature, but I'm wondering why it was done like this.

**Comment by maffoo** [comment]
It's because the current version of labrad does not allow '' (empty data) inside other pieces of data (e.g. clusters) but rather only at the top level. If the example you give were allowed, then you might expect to be able to supply a cluster of type `(i_)` for the two arguments, but that's not allowed. When you supply default values, pylabrad allows those arguments to be omitted so that you can pass in just `i`, but that's different that the cluster with an empty member.

I think it would be nice to change this restriction to allow embedded empties, as I think we've discussed, in which case the decorator could work as you've given it. This would probably be very hard to implement in LabVIEW, but at least for our purposes that's not really a big downside.

**Comment by DanielSank** [comment]
Groovy.
